from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from uuid import uuid4


class ConnectionState(str, Enum):
    """Lifecycle states for an external TCP connection."""

    CONNECTED = "CONNECTED"
    TLS_ESTABLISHED = "TLS_ESTABLISHED"
    AUTHENTICATING = "AUTHENTICATING"
    AUTHENTICATED = "AUTHENTICATED"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"


@dataclass
class ConnectionSession:
    """
    Thread-safe mutable session record for one external TCP client.

    ``connection_id`` is a UUID generated by CORE and is distinct from
    ``identity_id`` (device identity). One device may hold multiple
    connections. Timestamps use ``time.monotonic`` seconds so tests can
    inject a fake clock.
    """

    connection_id: str = field(default_factory=lambda: str(uuid4()))
    remote_address: str = ""
    connected_at: float = field(default_factory=time.monotonic)
    authenticated_at: float | None = None
    identity_id: str | None = None
    authenticated: bool = False
    last_activity: float = field(default_factory=time.monotonic)
    messages_received: int = 0
    messages_sent: int = 0
    state: ConnectionState = ConnectionState.CONNECTED

    def __post_init__(self) -> None:
        if not self.connection_id:
            raise ValueError("connection_id cannot be empty.")

    def touch(self, now: float | None = None) -> None:
        """Mark activity without changing authentication state."""
        self.last_activity = now if now is not None else time.monotonic()

    def mark_authenticated(
        self,
        identity_id: str,
        now: float | None = None,
    ) -> None:
        """Bind an authenticated device identity to this connection."""
        if not identity_id:
            raise ValueError("identity_id cannot be empty.")
        current = now if now is not None else time.monotonic()
        self.identity_id = identity_id
        self.authenticated = True
        self.authenticated_at = current
        self.last_activity = current
        self.state = ConnectionState.AUTHENTICATED

    def transition(self, state: ConnectionState) -> None:
        """Move the session to a new lifecycle state."""
        self.state = state


__all__ = ["ConnectionSession", "ConnectionState"]
