SYSTEM_STARTED = "SYSTEM_STARTED"
SYSTEM_STOPPED = "SYSTEM_STOPPED"

COMPONENT_STARTED = "COMPONENT_STARTED"
COMPONENT_STOPPED = "COMPONENT_STOPPED"
COMPONENT_FAILED = "COMPONENT_FAILED"

SERVICE_STARTED = "SERVICE_STARTED"
SERVICE_STOPPED = "SERVICE_STOPPED"
SERVICE_FAILED = "SERVICE_FAILED"
SERVICE_EXECUTED = "SERVICE_EXECUTED"

MESSAGE_SENT = "MESSAGE_SENT"
MESSAGE_RECEIVED = "MESSAGE_RECEIVED"

RESOURCE_REGISTERED = "RESOURCE_REGISTERED"
RESOURCE_REMOVED = "RESOURCE_REMOVED"
RESOURCE_UPDATED = "RESOURCE_UPDATED"

SECURITY_AUTHENTICATION_SUCCEEDED = "SECURITY_AUTHENTICATION_SUCCEEDED"
SECURITY_AUTHENTICATION_FAILED = "SECURITY_AUTHENTICATION_FAILED"
SECURITY_AUTHORIZATION_SUCCEEDED = "SECURITY_AUTHORIZATION_SUCCEEDED"
SECURITY_AUTHORIZATION_FAILED = "SECURITY_AUTHORIZATION_FAILED"
SECURITY_ACCESS_DENIED = "SECURITY_ACCESS_DENIED"

HEALTH_CHANGED = "HEALTH_CHANGED"

# Device / Agent runtime events for Windows co-hosted deployment
DEVICE_CONNECTED = "DEVICE_CONNECTED"
DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"
DEVICE_STATUS_CHANGED = "DEVICE_STATUS_CHANGED"

AGENT_STARTED = "AGENT_STARTED"
AGENT_STOPPED = "AGENT_STOPPED"
AGENT_FAILED = "AGENT_FAILED"

RUNTIME_STARTED = "RUNTIME_STARTED"
RUNTIME_STOPPED = "RUNTIME_STOPPED"
